<?php

namespace App\Imports;

use App\NilaiSkala4SMA;
use Maatwebsite\Excel\Concerns\ToModel;
use Maatwebsite\Excel\Concerns\WithStartRow;
class NilaiSkala4SMAImport implements ToModel, WithStartRow
{
    /**
    * @param array $row
    *
    * @return \Illuminate\Database\Eloquent\Model|null
    */
    public function __construct($d)
    {
        $this->kode_tahun_akademik= $d;
        //dd($this->kode_tahun_akademik);
    }
    public function startRow(): int
    {
        return 2;
    }
    public function model(array $row)
    {
        return new NilaiSkala4SMA([
            'nomor_pendaftaran' => $row[0],
            'kode_jurusan' => $row[1],
            'nama_jurusan' => $row[2],
            'IND1' => $row[3],
            'INDUnit1' => $row[4],
            'INDBasis1' => $row[5],
            'ING1' => $row[6],
            'INGUnit1' => $row[7],
            'INGBasis1' => $row[8],
            'MAT1' => $row[9],
            'MATUnit1' => $row[10],
            'MATBasis1' => $row[11],
            'bio1' => $row[12],
            'biounit1' => $row[13],
            'biobasis1' => $row[14],
            'fis1' => $row[15],
            'fisunit1' => $row[16],
            'fisbasis1' => $row[17],
            'kim1' => $row[18],
            'kimunit1' => $row[19],
            'kimbasis1' => $row[20],
            'eko1' => $row[21],
            'ekounit1' => $row[22],
            'ekobasis1' => $row[23],
            'geo1' => $row[24],
            'geounit1' => $row[25],
            'geobasis1' => $row[26],
            'sos1' => $row[27],
            'sosunit1' => $row[28],
            'sosbasis1' => $row[29],
            'bas1' => $row[30],
            'basunit1' => $row[31],
            'basbasis1' => $row[32],
            'sba1' => $row[33],
            'sbaunit1' => $row[34],
            'sbabasis1' => $row[35],
            'sid1' => $row[36],
            'sidunit1' => $row[37],
            'sidbasis1' => $row[38],

            'IND2' => $row[39],
            'INDUnit2' => $row[40],
            'INDBasis2' => $row[41],
            'ING2' => $row[42],
            'INGUnit2' => $row[43],
            'INGBasis2' => $row[44],
            'MAT2' => $row[45],
            'MATUnit2' => $row[46],
            'MATBasis2' => $row[47],
            'bio2' => $row[48],
            'biounit2' => $row[49],
            'biobasis2' => $row[50],
            'fis2' => $row[51],
            'fisunit2' => $row[52],
            'fisbasis2' => $row[53],
            'kim2' => $row[54],
            'kimunit2' => $row[55],
            'kimbasis2' => $row[56],
            'eko2' => $row[57],
            'ekounit2' => $row[58],
            'ekobasis2' => $row[59],
            'geo2' => $row[60],
            'geounit2' => $row[61],
            'geobasis2' => $row[62],
            'sos2' => $row[63],
            'sosunit2' => $row[64],
            'sosbasis2' => $row[65],
            'bas2' => $row[66],
            'basunit2' => $row[67],
            'basbasis2' => $row[68],
            'sba2' => $row[69],
            'sbaunit2' => $row[70],
            'sbabasis2' => $row[71],
            'sid2' => $row[72],
            'sidunit2' => $row[73],
            'sidbasis2' => $row[74],

            'IND3' => $row[75],
            'INDUnit3' => $row[76],
            'INDBasis3' => $row[77],
            'ING3' => $row[78],
            'INGUnit3' => $row[79],
            'INGBasis3' => $row[80],
            'MAT3' => $row[81],
            'MATUnit3' => $row[82],
            'MATBasis3' => $row[83],
            'bio3' => $row[84],
            'biounit3' => $row[85],
            'biobasis3' => $row[86],
            'fis3' => $row[87],
            'fisunit3' => $row[88],
            'fisbasis3' => $row[89],
            'kim3' => $row[90],
            'kimunit3' => $row[91],
            'kimbasis3' => $row[92],
            'eko3' => $row[93],
            'ekounit3' => $row[94],
            'ekobasis3' => $row[95],
            'geo3' => $row[96],
            'geounit3' => $row[97],
            'geobasis3' => $row[98],
            'sos3' => $row[99],
            'sosunit3' => $row[100],
            'sosbasis3' => $row[101],
            'bas3' => $row[102],
            'basunit3' => $row[103],
            'basbasis3' => $row[104],
            'sba3' => $row[105],
            'sbaunit3' => $row[106],
            'sbabasis3' => $row[107],
            'sid3' => $row[108],
            'sidunit3' => $row[109],
            'sidbasis3' => $row[110],

            'IND4' => $row[111],
            'INDUnit4' => $row[112],
            'INDBasis4' => $row[113],
            'ING4' => $row[114],
            'INGUnit4' => $row[115],
            'INGBasis4' => $row[116],
            'MAT4' => $row[117],
            'MATUnit4' => $row[118],
            'MATBasis4' => $row[119],
            'bio4' => $row[120],
            'biounit4' => $row[121],
            'biobasis4' => $row[122],
            'fis4' => $row[123],
            'fisunit4' => $row[124],
            'fisbasis4' => $row[125],
            'kim4' => $row[126],
            'kimunit4' => $row[127],
            'kimbasis4' => $row[128],
            'eko4' => $row[129],
            'ekounit4' => $row[130],
            'ekobasis4' => $row[131],
            'geo4' => $row[132],
            'geounit4' => $row[133],
            'geobasis4' => $row[134],
            'sos4' => $row[135],
            'sosunit4' => $row[136],
            'sosbasis4' => $row[137],
            'bas4' => $row[138],
            'basunit4' => $row[139],
            'basbasis4' => $row[140],
            'sba4' => $row[141],
            'sbaunit4' => $row[142],
            'sbabasis4' => $row[143],
            'sid4' => $row[144],
            'sidunit4' => $row[145],
            'sidbasis4' => $row[146],

            'IND5' => $row[147],
            'INDUnit5' => $row[148],
            'INDBasis5' => $row[149],
            'ING5' => $row[150],
            'INGUnit5' => $row[151],
            'INGBasis5' => $row[152],
            'MAT5' => $row[153],
            'MATUnit5' => $row[154],
            'MATBasis5' => $row[155],
            'bio5' => $row[156],
            'biounit5' => $row[157],
            'biobasis5' => $row[158],
            'fis5' => $row[159],
            'fisunit5' => $row[160],
            'fisbasis5' => $row[161],
            'kim5' => $row[162],
            'kimunit5' => $row[163],
            'kimbasis5' => $row[164],
            'eko5' => $row[165],
            'ekounit5' => $row[166],
            'ekobasis5' => $row[167],
            'geo5' => $row[168],
            'geounit5' => $row[169],
            'geobasis5' => $row[170],
            'sos5' => $row[171],
            'sosunit5' => $row[172],
            'sosbasis5' => $row[173],
            'bas5' => $row[174],
            'basunit5' => $row[175],
            'basbasis5' => $row[176],
            'sba5' => $row[177],
            'sbaunit5' => $row[178],
            'sbabasis5' => $row[179],
            'sid5' => $row[180],
            'sidunit5' => $row[181],
            'sidbasis5' => $row[182],

            'IND6' => $row[183],
            'INDUnit6' => $row[184],
            'INDBasis6' => $row[185],
            'ING6' => $row[186],
            'INGUnit6' => $row[187],
            'INGBasis6' => $row[188],
            'MAT6' => $row[189],
            'MATUnit6' => $row[190],
            'MATBasis6' => $row[191],
            'bio6' => $row[192],
            'biounit6' => $row[193],
            'biobasis6' => $row[194],
            'fis6' => $row[195],
            'fisunit6' => $row[196],
            'fisbasis6' => $row[197],
            'kim6' => $row[198],
            'kimunit6' => $row[199],
            'kimbasis6' => $row[200],
            'eko6' => $row[201],
            'ekounit6' => $row[202],
            'ekobasis6' => $row[203],
            'geo6' => $row[204],
            'geounit6' => $row[205],
            'geobasis6' => $row[206],
            'sos6' => $row[207],
            'sosunit6' => $row[208],
            'sosbasis6' => $row[209],
            'bas6' => $row[210],
            'basunit6' => $row[211],
            'basbasis6' => $row[212],
            'sba6' => $row[213],
            'sbaunit6' => $row[214],
            'sbabasis6' => $row[215],
            'sid6' => $row[216],
            'sidunit6' => $row[217],
            'sidbasis6' => $row[218],
            'kode_tahun_akademik' => $this->kode_tahun_akademik,

        ]);
    }
}
